services:
  jenkins:
    build: ./jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
    environment:
      - JENKINS_USERNAME=${JENKINS_USERNAME}
      - JENKINS_PASSWORD=${JENKINS_PASSWORD}
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins/init.groovy.d:/var/jenkins_home/init.groovy.d

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_playwright
    depends_on:
      - jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins/wait_for_jenkins.sh:/wait.sh
    entrypoint: ["/bin/bash", "/wait.sh"]
    command: pytest -s -v $TESTS

volumes:
  jenkins_home:
