name: Playwright + Jenkins

on:
  pull_request:
    branches:
      - main

jobs:
  run-pytest:
    name: Run pytest tests
    runs-on: ubuntu-latest
    permissions:
      contents: read  # достаточно, если нет push

    env:
      JENKINS_USERNAME: ${{ secrets.ADMIN_USERNAME }}
      JENKINS_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      HOST: ${{ secrets.BASE_URL }}
      PORT: ${{ secrets.BASE_PORT }}
      HEADLESS_MODE: ${{ secrets.HEADLESS_MODE }}

    steps:
      # -------------------
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false
          clean: true

      # -------------------
      - name: Detect changed test files
        id: changed-tests
        uses: step-security/changed-files@v45
        with:
          files: |
            tests/**/*.py

      # -------------------
      - name: Set CHANGED_TESTS variable
        run: |
          if [ "${{ steps.changed-tests.outputs.any_changed }}" = "true" ]; then
            FIXED_TESTS=$(echo "${{ steps.changed-tests.outputs.all_changed_files }}" | sed 's/pipeline_project/pipeline_projects/g')
            echo "CHANGED_TESTS=$FIXED_TESTS" >> $GITHUB_ENV
          else
            echo "No test changes — running ALL tests"
            echo "CHANGED_TESTS=tests" >> $GITHUB_ENV
          fi

      # -------------------
      - name: Create .env file for Docker Compose
        run: |
          cat > .env <<EOF
          JENKINS_USERNAME=${JENKINS_USERNAME}
          JENKINS_PASSWORD=${JENKINS_PASSWORD}
          HOST=${HOST}
          PORT=${PORT}
          HEADLESS_MODE=${HEADLESS_MODE}
          EOF

      # -------------------
      - name: Run Docker Compose
        env:
          TESTS: ${{ env.CHANGED_TESTS }}
        run: |
          docker compose up --build --abort-on-container-exit --exit-code-from tests
