name: Playwright + Jenkins

on:
  pull_request:
    branches:
      - main

jobs:
  run-pytest:
    name: Run Playwright tests
    runs-on: ubuntu-latest

    env:
      JENKINS_USERNAME: ${{ secrets.ADMIN_USERNAME }}
      JENKINS_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      HOST: ${{ secrets.BASE_URL }}
      PORT: ${{ secrets.BASE_PORT }}
      HEADLESS_MODE: ${{ secrets.HEADLESS_MODE }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Detect changed test files
        id: changed-tests
        uses: step-security/changed-files@v45
        with:
          files: |
            tests/**/*.py

      - name: Set test paths
        run: |
          if [ "${{ steps.changed-tests.outputs.any_changed }}" = "true" ]; then
            echo "TEST_PATHS=${{ steps.changed-tests.outputs.all_changed_files }}" >> $GITHUB_ENV
          else
            echo "TEST_PATHS=tests" >> $GITHUB_ENV
          fi

      - name: Create .env file
        run: |
          echo "JENKINS_USERNAME=${JENKINS_USERNAME}" > .env
          echo "JENKINS_PASSWORD=${JENKINS_PASSWORD}" >> .env
          echo "HOST=${HOST}" >> .env
          echo "PORT=${PORT}" >> .env
          echo "HEADLESS_MODE=${HEADLESS_MODE}" >> .env

      - name: Run pytest
        run: |
          pytest $TEST_PATHS -vv -p no:cacheprovider
